// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbmv7HJ36p28UqwjvXgjNipe71iuh6cEk',
    appId: '1:73366339597:web:22cb154cb15ef3eea85544',
    messagingSenderId: '73366339597',
    projectId: 'queue2-flutter',
    authDomain: 'queue2-flutter.firebaseapp.com',
    storageBucket: 'queue2-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5fVv4PLacY-xoyXqPrPOyM4laf7d1cpc',
    appId: '1:73366339597:android:3460e1096716440da85544',
    messagingSenderId: '73366339597',
    projectId: 'queue2-flutter',
    storageBucket: 'queue2-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-VGVJKkpWdDDEmGah-rmpe1sAsNiYFI0',
    appId: '1:73366339597:ios:5de8a212918ba19ba85544',
    messagingSenderId: '73366339597',
    projectId: 'queue2-flutter',
    storageBucket: 'queue2-flutter.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-VGVJKkpWdDDEmGah-rmpe1sAsNiYFI0',
    appId: '1:73366339597:ios:5de8a212918ba19ba85544',
    messagingSenderId: '73366339597',
    projectId: 'queue2-flutter',
    storageBucket: 'queue2-flutter.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbmv7HJ36p28UqwjvXgjNipe71iuh6cEk',
    appId: '1:73366339597:web:a23315ca1a111b4fa85544',
    messagingSenderId: '73366339597',
    projectId: 'queue2-flutter',
    authDomain: 'queue2-flutter.firebaseapp.com',
    storageBucket: 'queue2-flutter.appspot.com',
  );
}
